<style lang='scss' scoped src='./style.scss'>

</style>
<template>
    <div class="record">
        <div class="r_center">
            <div class="boxone">
                <h5>竞猜时间：6-20&nbsp;&nbsp;22:00:11</h5>
                <table>

                    <tr>
                        <td>竞猜轮次</td>
                        <td>精彩方案</td>
                        <td>赛果</td>
                    </tr>
                    <tr>
                        <td>16强</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                            <p>埃及</p>
                            <p>乌拉圭</p>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                            <p>埃及</p>
                            <p>乌拉圭</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr>
                        <td>8强</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                            <p>埃及</p>
                            <p>乌拉圭</p>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                            <p>埃及</p>
                            <p>乌拉圭</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr>
                        <td>4强</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr>
                        <td>冠亚军</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr>
                        <td>冠军</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr class="list">
                        <td>终极大奖</td>
                        <td>
                            <p>所有名单都猜中，即可瓜分20万大奖</p>
                        </td>
                        <td>待确定</td>
                    </tr>
                </table>
            </div>
            <div class="boxone">
                <h5>竞猜时间：6-20&nbsp;&nbsp;22:00:11</h5>
                <table>
                    <tr>
                        <td>竞猜轮次</td>
                        <td>精彩方案</td>
                        <td>赛果</td>
                    </tr>
                    <tr>
                        <td>8强</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                            <p>埃及</p>
                            <p>乌拉圭</p>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                            <p>埃及</p>
                            <p>乌拉圭</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr>
                        <td>4强</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr>
                        <td>冠亚军</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr>
                        <td>冠军</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                </table>
            </div>
            <div class="boxone">
                <h5>竞猜时间：6-20&nbsp;&nbsp;22:00:11</h5>
                <table>
                    <tr>
                        <td>竞猜轮次</td>
                        <td>精彩方案</td>
                        <td>赛果</td>
                    </tr>
                    <tr>
                        <td>4强</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr>
                        <td>冠亚军</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                    <tr>
                        <td>冠军</td>
                        <td>
                            <p>俄罗斯</p>
                            <p>沙特</p>
                        </td>
                        <td>待开奖</td>
                    </tr>
                </table>
            </div>
            <table>
                <tr class="table_list">
                    <td>16强</td>
                    <td>8强</td>
                    <td>4强</td>
                    <td>冠亚军</td>
                    <td>冠军</td>
                    <td>终极大奖</td>
                </tr>
                <tr class="table_list">
                    <td>15万</td>
                    <td>8万</td>
                    <td>4万</td>
                    <td>2万</td>
                    <td>1万</td>
                    <td>20万</td>
                </tr>
            </table>
            <div class="prize">
                <span>终极大奖：</span>猜对16强、8强、4强、冠亚军和冠军所有赛果，可评分20万巨额奖金
            </div>
            <div class="prize">
                <span>阶段分奖：</span>（每阶段猜对赛果，均可平分巨额奖金）
            </div>
        </div>

        <button class="paymentBtn" >
            竞猜赛果
        </button>
    </div>
</template>